spring.application.name=backend-connectivity
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/skillstack
spring.datasource.username=root
spring.datasource.password=Neha@2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nehaym1046@gmail.com
spring.mail.password=ipstqqnrlpuepjcr   
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

paypal.client.id=ATVBnEd2qAw6uxxBpzNUqCbtkndlQAhnc7WDHWhnxgN4UC0GkL7pq9tcQ3s0N58Fl-4bhTv7m9j-m_DR
paypal.client.secret=EDDyDqTEJUkRy-krBwJT4duCKyouUtgxstnKuf0e-pTLIqfixBFxQIZXCLI5e21Z04EQHtgwZJuve6PA
paypal.mode=sandbox
